# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\fconfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_config(object):
    def setupUi(self, config):
        config.setObjectName("config")
        config.setWindowModality(QtCore.Qt.WindowModal)
        config.resize(403, 179)
        self.btPesqCamTess = QtWidgets.QPushButton(config)
        self.btPesqCamTess.setGeometry(QtCore.QRect(360, 40, 25, 20))
        self.btPesqCamTess.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Imagens/diretorio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btPesqCamTess.setIcon(icon)
        self.btPesqCamTess.setObjectName("btPesqCamTess")
        self.btGravar = QtWidgets.QPushButton(config)
        self.btGravar.setGeometry(QtCore.QRect(150, 140, 75, 23))
        self.btGravar.setObjectName("btGravar")
        self.txtCamTess = QtWidgets.QLineEdit(config)
        self.txtCamTess.setGeometry(QtCore.QRect(20, 40, 341, 20))
        self.txtCamTess.setObjectName("txtCamTess")
        self.label = QtWidgets.QLabel(config)
        self.label.setGeometry(QtCore.QRect(20, 20, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(config)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 191, 16))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(config)
        self.line.setGeometry(QtCore.QRect(0, 60, 411, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.cbTipoDocumento = QtWidgets.QComboBox(config)
        self.cbTipoDocumento.setGeometry(QtCore.QRect(20, 90, 341, 22))
        self.cbTipoDocumento.setObjectName("cbTipoDocumento")
        self.cbTipoDocumento.addItem("")
        self.cbTipoDocumento.addItem("")
        self.line_2 = QtWidgets.QFrame(config)
        self.line_2.setGeometry(QtCore.QRect(0, 110, 401, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(config)
        QtCore.QMetaObject.connectSlotsByName(config)

    def retranslateUi(self, config):
        _translate = QtCore.QCoreApplication.translate
        config.setWindowTitle(_translate("config", "Configurações"))
        self.btGravar.setText(_translate("config", "Gravar"))
        self.label.setText(_translate("config", "Caminho Tesseract"))
        self.label_2.setText(_translate("config", "Marcador Padrão tipo de documento"))
        self.cbTipoDocumento.setItemText(0, _translate("config", "Cupom"))
        self.cbTipoDocumento.setItemText(1, _translate("config", "Nota Fiscal"))
